-- MySQL Script generated by MySQL Workbench
-- Wed Dec 31 05:03:46 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema laboraja
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema laboraja
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `laboraja` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `laboraja` ;

-- -----------------------------------------------------
-- Table `laboraja`.`client`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `laboraja`.`client` (
  `idClient` INT NOT NULL AUTO_INCREMENT,
  `nom client` VARCHAR(45) NOT NULL,
  `telephone` VARCHAR(45) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idClient`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `laboraja`.`analyses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `laboraja`.`analyses` (
  `idanalyses` INT NOT NULL AUTO_INCREMENT,
  `analyses bacteriologique` VARCHAR(100) NOT NULL,
  `analyses physicochimique` VARCHAR(100) NOT NULL,
  `idclient` INT NOT NULL,
  PRIMARY KEY (`idanalyses`),
  INDEX `fk_analyses_client_idx` (`idclient` ASC) VISIBLE,
  CONSTRAINT `fk_analyses_client`
    FOREIGN KEY (`idclient`)
    REFERENCES `laboraja`.`client` (`idClient`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
